const enumSkills = {
    angular: 'Angular',
    netCore: '.Net core',
    html: 'HTML',
    css: 'CSS',
    bootstrap: 'Bootstrap',
    angularMaterial: 'Angular Material',
    materialize: 'Materialize',
    vanilla: 'Vanilla.js',
    jQuery: 'JQuery',
    jQueryUI: 'JQuery UI',
    vue: 'Vue.js',
    react: 'React.js',
    reactNative: 'React-native',
    ionic: 'Ionic',
    flutter: 'Flutter',
    php: 'PHP',
    codeigniter: 'Codeigniter',
    sql: 'MS SQL',
    mySql: 'MySql',
    firebase: 'Firebase'
}